force-app/main/default/objects/HCK_JunctionContactQuiz__c/HCK_JunctionContactQuiz__c.object-meta.xml
<CustomObject>
    <label>JunctionContactQuiz</label>
    <nameField>
        <label>JunctionContactQuiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JunctionContactQuizs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCK_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>JunctionContactQuizs</relationshipLabel>
    <relationshipName>JunctionContactQuizs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Is_Taken__c.field-meta.xml
<CustomField>
    <fullName>HCK_Is_Taken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Taken..?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Quiz__c.field-meta.xml
<CustomField>
    <fullName>HCK_Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>HCK_Quiz__c</referenceTo>
    <relationshipLabel>JunctionContactQuizs</relationshipLabel>
    <relationshipName>JunctionContactQuizs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_Quiz__c/HCK_Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HCK_QuizController.cls
public class HCK_QuizController{
    
    @AuraEnabled
    public static List<quizWrapper> getQuizList(string contactId){
        
        set<string> quizIds = new set<string>();
        List<quizWrapper> quizMapping = new List<quizWrapper>();
        for(HCK_JunctionContactQuiz__c quizCon : [select HCK_Quiz__c,HCK_Quiz__r.Name,Id from HCK_JunctionContactQuiz__c where HCK_Contact__c = :contactId and HCK_Is_Taken__c=false]){
            
            quizMapping.add(new quizWrapper(string.valueof(quizCon.HCK_Quiz__c),string.valueof(quizCon.HCK_Quiz__r.name),string.valueof(quizCon.Id)));

        }
        
        return quizMapping;
    }
    
    public class quizWrapper{
        
        @AuraEnabled
        public string quizId{get;set;}
        @AuraEnabled
        public string quizName{get;set;}
        @AuraEnabled
        public string junctionId{get;set;}
        
        public quizWrapper(string idValue, string nameValue,string juncId){
            quizId = idValue;
            quizName=nameValue;
            junctionId = juncId;
        }
    }
}