force-app/main/default/objects/HCK_Answer__c/HCK_Answer__c.object-meta.xml
<CustomObject>
    <label>HCK_Answer</label>
    <nameField>
        <displayFormat>Answers-{00000}</displayFormat>
        <label>Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCK_Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_Answer__c/fields/HCK_AnswerValue__c.field-meta.xml
<CustomField>
    <fullName>HCK_AnswerValue__c</fullName>
    <description>Answers text to be stored here</description>
    <label>HCK_AnswerValue</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/HCK_JunctionContactQuiz__c.object-meta.xml
<CustomObject>
    <label>JunctionContactQuiz</label>
    <nameField>
        <label>JunctionContactQuiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JunctionContactQuizs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCK_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>JunctionContactQuizs</relationshipLabel>
    <relationshipName>JunctionContactQuizs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Is_Taken__c.field-meta.xml
<CustomField>
    <fullName>HCK_Is_Taken__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Taken..?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionContactQuiz__c/fields/HCK_Quiz__c.field-meta.xml
<CustomField>
    <fullName>HCK_Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>HCK_Quiz__c</referenceTo>
    <relationshipLabel>JunctionContactQuizs</relationshipLabel>
    <relationshipName>JunctionContactQuizs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionQuizQuestion__c/HCK_JunctionQuizQuestion__c.object-meta.xml
<CustomObject>
    <label>JunctionQuizQuestion</label>
    <nameField>
        <label>JunctionQuizQuestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JunctionQuizQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_JunctionQuizQuestion__c/fields/HCK_Question__c.field-meta.xml
<CustomField>
    <fullName>HCK_Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>JunctionQuizQuestions</relationshipLabel>
    <relationshipName>JunctionQuizQuestions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_JunctionQuizQuestion__c/fields/HCK_Quiz__c.field-meta.xml
<CustomField>
    <fullName>HCK_Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>HCK_Quiz__c</referenceTo>
    <relationshipLabel>JunctionQuizQuestions</relationshipLabel>
    <relationshipName>JunctionQuizQuestions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_QuestionsAnswer__c/HCK_QuestionsAnswer__c.object-meta.xml
<CustomObject>
    <label>HCK_QuestionsAnswer</label>
    <nameField>
        <displayFormat>HCK_Q&amp;A-{00000}</displayFormat>
        <label>HCK_QuestionsAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCK_QuestionsAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/HCK_Answer__c.field-meta.xml
<CustomField>
    <fullName>HCK_Answer__c</fullName>
    <label>HCK_Answer</label>
    <referenceTo>HCK_Answer__c</referenceTo>
    <relationshipLabel>HCK_QuestionsAnswers</relationshipLabel>
    <relationshipName>HCK_QuestionsAnswers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this answer correct ?</description>
    <label>Is Correct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>HCK_QuestionsAnswers</relationshipLabel>
    <relationshipName>HCK_QuestionsAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_Quiz__c/HCK_Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/QuestionValue__c.field-meta.xml
<CustomField>
    <fullName>QuestionValue__c</fullName>
    <description>Stores questions for text</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StudentselectedAnswer__c/StudentselectedAnswer__c.object-meta.xml
<CustomObject>
    <label>StudentselectedAnswer</label>
    <nameField>
        <label>StudentselectedAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentselectedAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/HCK_QuestionAnswers.cls
public class HCK_QuestionAnswers{
    
    @AuraEnabled
    public static Boolean validateContact(string contactId,string quizId){
        List<HCK_JunctionContactQuiz__c> lstcCmQuiz = [SELECT Id FROM HCK_JunctionContactQuiz__c WHERE HCK_Contact__c =:contactId AND HCK_Quiz__c =:quizId ];
        if(lstcCmQuiz.Size() > 0 ) {
            return true ;
        }
        else {
            return false ;
        }
    }
    
    @AuraEnabled
    public static Boolean submitQuizQuestions(List<StudentselectedAnswer__c> userAnswers, HCK_JunctionContactQuiz__c quizObj) {
        
        //system.debug(quizObjId);
        //HCK_JunctionContactQuiz__c quizObj =  [Select id From HCK_JunctionContactQuiz__c Where id = :quizObjId Limit 1];
        //quizObj.HCK_Is_Taken__c = true;
        update quizObj;
        insert userAnswers;
        return true;
    }
    
    @AuraEnabled
    public static List<QustiAnsweWrapper > getQuizQuestions(string contactId,string quizId){
        Boolean isValidContact = validateContact(contactId,quizId);
        
        if(isValidContact ) {
            List<QustiAnsweWrapper> lstQAWrapper = new List<QustiAnsweWrapper>();
            set<Id> questionsId = new set<Id>();
            Map<Id,HCK_QuestionsAnswer__c> mapQuestionWithQA = new Map<Id,HCK_QuestionsAnswer__c>();
            List<HCK_JunctionQuizQuestion__c> lstQuizQuestion = [SELECT Id,HCK_Question__c FROM HCK_JunctionQuizQuestion__c Where HCK_Quiz__c =:quizId ];
            for(HCK_JunctionQuizQuestion__c objQuizQuest : lstQuizQuestion ) {
                questionsId.add(objQuizQuest.HCK_Question__c );
            }
            for(Question__c objQuestion : [select Id,QuestionValue__c,(Select Id,HCK_Answer__c,HCK_Answer__r.HCK_AnswerValue__c,Is_Correct__c,Question__c from HCK_QuestionsAnswers__r) from Question__c Where Id IN :questionsId  ]) {
                
            }
            for(Question__c objQuestion : [select Id,QuestionValue__c,(Select Id,HCK_Answer__c,HCK_Answer__r.HCK_AnswerValue__c,Is_Correct__c,Question__c from HCK_QuestionsAnswers__r) from Question__c Where Id IN :questionsId  ]) {
                QustiAnsweWrapper objQAWrpper = new QustiAnsweWrapper ();
                objQAWrpper.question = objQuestion ;
                objQAWrpper.quesOptions = objQuestion.HCK_QuestionsAnswers__r ;
                if(objQuestion.HCK_QuestionsAnswers__r.size() > 2) {
                    objQAWrpper.questionType = 'checkbox' ;
                }
                else {
                    objQAWrpper.questionType = 'radio';
                }
                lstQAWrapper.add(objQAWrpper);
            }
            
            
            /**for(HCK_QuestionsAnswer__c objQuestionAnswer : [Select Question__c,HCK_Answer__c from HCK_QuestionsAnswer__c Where Question__c In :questionsId ]) {
               if(mapQuesIdWithQuesAnswe.containsKey(objQuestionAnswer.Question__c)) {
                   mapQuesIdWithQuesAnswe.get(objQuestionAnswer.Question__c).add(objQuestionAnswer );
               }
               else {
                   mapQuesIdWithQuesAnswe.put(objQuestionAnswer.Question__c,new List<HCK_QuestionsAnswer__c >(objQuestionAnswer ));
               }
            }**/
            return lstQAWrapper  ;
        }
        else {
            return null;
        }
    }
    
    public class QustiAnsweWrapper {
    
        @AuraEnabled
        public Question__c question{get;set;}
        @AuraEnabled
        public List<HCK_QuestionsAnswer__c > quesOptions{get;set;}
        @AuraEnabled
        public String questionType{get;set;}
        
        
    
    }
    
}