force-app/main/default/objects/HCK_Answer__c/HCK_Answer__c.object-meta.xml
<CustomObject>
    <label>HCK_Answer</label>
    <nameField>
        <displayFormat>Answers-{00000}</displayFormat>
        <label>Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCK_Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_QuestionsAnswer__c/HCK_QuestionsAnswer__c.object-meta.xml
<CustomObject>
    <label>HCK_QuestionsAnswer</label>
    <nameField>
        <displayFormat>HCK_Q&amp;A-{00000}</displayFormat>
        <label>HCK_QuestionsAnswer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCK_QuestionsAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/HCK_Answer__c.field-meta.xml
<CustomField>
    <fullName>HCK_Answer__c</fullName>
    <label>HCK_Answer</label>
    <referenceTo>HCK_Answer__c</referenceTo>
    <relationshipLabel>HCK_QuestionsAnswers</relationshipLabel>
    <relationshipName>HCK_QuestionsAnswers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/Is_Correct__c.field-meta.xml
<CustomField>
    <fullName>Is_Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this answer correct ?</description>
    <label>Is Correct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HCK_QuestionsAnswer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>HCK_QuestionsAnswers</relationshipLabel>
    <relationshipName>HCK_QuestionsAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentselectedAnswer__c/StudentselectedAnswer__c.object-meta.xml
<CustomObject>
    <label>StudentselectedAnswer</label>
    <nameField>
        <label>StudentselectedAnswer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentselectedAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentselectedAnswer__c/fields/QuestionsAnswer__c.field-meta.xml
<CustomField>
    <fullName>QuestionsAnswer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuestionsAnswer</label>
    <referenceTo>HCK_QuestionsAnswer__c</referenceTo>
    <relationshipLabel>StudentselectedAnswers</relationshipLabel>
    <relationshipName>StudentselectedAnswers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentselectedAnswer__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz</label>
    <referenceTo>HCK_Quiz__c</referenceTo>
    <relationshipLabel>StudentselectedAnswers</relationshipLabel>
    <relationshipName>StudentselectedAnswers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StudentselectedAnswer__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>StudentselectedAnswers</relationshipLabel>
    <relationshipName>StudentselectedAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HCK_QuizSummary.cls
public class HCK_QuizSummary{
    
    @AuraEnabled
    public static string getselectedAnswers(String candidateId, string QuizId){ 
    map<string,set<string>> answerList = new map<string,set<string>>();
    set<string> junctionId = new set<string>();
        List<StudentselectedAnswer__c> answerListVal = [select Quiz__c,QuestionsAnswer__c,QuestionsAnswer__r.Question__c,QuestionsAnswer__r.HCK_Answer__c from StudentselectedAnswer__c where Quiz__c =:QuizId and Student__c=:candidateId];
        for(StudentselectedAnswer__c ans : answerListVal){
            junctionId.add(ans.QuestionsAnswer__r.Question__c);
            if(answerList.keyset().contains(ans.QuestionsAnswer__r.Question__c)){
                answerList.get(ans.QuestionsAnswer__r.Question__c).add(ans.QuestionsAnswer__r.HCK_Answer__c);
            }
            else{
                set<string> answerValues = new set<string>();
                answerValues.add(ans.QuestionsAnswer__r.HCK_Answer__c);
                answerList.put(ans.QuestionsAnswer__r.Question__c,answerValues);
            }
        }
        
        map<string,list<string>> actualAnswerList = new map<string,list<string>>();
        List<HCK_QuestionsAnswer__c> questionList = new List<HCK_QuestionsAnswer__c>();
        questionList = [select Question__c,HCK_Answer__c,Is_Correct__c from HCK_QuestionsAnswer__c where Question__c IN :junctionId and Is_Correct__c=true];
        for(HCK_QuestionsAnswer__c actualAns: questionList) {
            if(actualAnswerList.keyset().contains(actualAns.Question__c)){
                actualAnswerList.get(actualAns.Question__c).add(actualAns.HCK_Answer__c);
            }
            else{
                list<string> answerValues = new list<string>();
                answerValues.add(actualAns.HCK_Answer__c);
                actualAnswerList.put(actualAns.Question__c,answerValues);
            }
        }
        
        Integer totalQuestions = actualAnswerList.keyset().size();
        Integer correctAnswers = 0;
        for(string question : actualAnswerList.keyset()){
            system.debug(question);
            system.debug(answerList.get(question)+'   '+answerList.keyset());
            system.debug(actualAnswerList.get(question)+'   '+actualAnswerList.keyset());           
            if(answerList.get(question).containsall(actualAnswerList.get(question))) {
                correctAnswers = correctAnswers+1;
            }
        }
        
        return string.valueof(totalQuestions)+'%%%%'+string.valueof(correctAnswers);
    }
    
}